version: '3.8'

services:
  web:
    build: .  #this line is used to build docker images from Dockerfile located in the current dir when we run docker-compose up it will look for Dockerfile specified in the dir
    command: gunicorn --bind 0.0.0.0:8875 blogsite.wsgi:application  # this will execute the run the application inside the container.
    volumes:
      - .:/app
    ports:
      - "8875:8875"
    environment:
      - DEBUG=1
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
